input.onButtonPressed(Button.A, function () {
    serial.writeString("D:")
    serial.writeNumber(input.lightLevel())
    serial.writeString(",")
    serial.writeNumber(input.acceleration(Dimension.X))
    serial.writeLine("")
    basic.pause(100)
})
basic.forever(function () {
    led.plot(0, 0)
    serial.writeString("D:")
    serial.writeNumber(input.lightLevel())
    serial.writeString(",")
    serial.writeNumber(input.acceleration(Dimension.X))
    serial.writeLine("")
    basic.pause(500)
    led.unplot(0, 0)
    basic.pause(200)
})
